
  name: swift5
  version: '5.1.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: The Swift Programming Language
  description: |
    Swift is a general-purpose programming language built using a modern
    approach to safety, performance, and software design patterns.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
